// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_qs2Y0jVL53cg21VDp3TxJzcfLyBurBw',
    appId: '1:561779744124:web:baa5f9d7d614ac43d9d8f9',
    messagingSenderId: '561779744124',
    projectId: 'batanghenyo-9f4ac',
    authDomain: 'batanghenyo-9f4ac.firebaseapp.com',
    storageBucket: 'batanghenyo-9f4ac.firebasestorage.app',
    measurementId: 'G-G700CB2W2B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeQNVutvGqgGclWcqecq27l9QyUwwnXbs',
    appId: '1:561779744124:android:850e34fda387d5e7d9d8f9',
    messagingSenderId: '561779744124',
    projectId: 'batanghenyo-9f4ac',
    storageBucket: 'batanghenyo-9f4ac.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_qs2Y0jVL53cg21VDp3TxJzcfLyBurBw',
    appId: '1:561779744124:web:8134144c1ccbf3c4d9d8f9',
    messagingSenderId: '561779744124',
    projectId: 'batanghenyo-9f4ac',
    authDomain: 'batanghenyo-9f4ac.firebaseapp.com',
    storageBucket: 'batanghenyo-9f4ac.firebasestorage.app',
    measurementId: 'G-HPQY270CPN',
  );
}
